//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prova.WCF.Client.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/Prova.Core.Model")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Prova.WCF.Client.ServiceReference.Ordine[] OrdiniField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceCliente {
            get {
                return this.CodiceClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceClienteField, value) != true)) {
                    this.CodiceClienteField = value;
                    this.RaisePropertyChanged("CodiceCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome {
            get {
                return this.CognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeField, value) != true)) {
                    this.CognomeField = value;
                    this.RaisePropertyChanged("Cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Prova.WCF.Client.ServiceReference.Ordine[] Ordini {
            get {
                return this.OrdiniField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdiniField, value) != true)) {
                    this.OrdiniField = value;
                    this.RaisePropertyChanged("Ordini");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ordine", Namespace="http://schemas.datacontract.org/2004/07/Prova.Core.Model")]
    [System.SerializableAttribute()]
    public partial class Ordine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Prova.WCF.Client.ServiceReference.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceOrdineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceProdottoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataOrdineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImportoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Prova.WCF.Client.ServiceReference.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceOrdine {
            get {
                return this.CodiceOrdineField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceOrdineField, value) != true)) {
                    this.CodiceOrdineField = value;
                    this.RaisePropertyChanged("CodiceOrdine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceProdotto {
            get {
                return this.CodiceProdottoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceProdottoField, value) != true)) {
                    this.CodiceProdottoField = value;
                    this.RaisePropertyChanged("CodiceProdotto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataOrdine {
            get {
                return this.DataOrdineField;
            }
            set {
                if ((this.DataOrdineField.Equals(value) != true)) {
                    this.DataOrdineField = value;
                    this.RaisePropertyChanged("DataOrdine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Importo {
            get {
                return this.ImportoField;
            }
            set {
                if ((this.ImportoField.Equals(value) != true)) {
                    this.ImportoField = value;
                    this.RaisePropertyChanged("Importo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClienti", ReplyAction="http://tempuri.org/IService/GetClientiResponse")]
        Prova.WCF.Client.ServiceReference.Cliente[] GetClienti();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClienti", ReplyAction="http://tempuri.org/IService/GetClientiResponse")]
        System.Threading.Tasks.Task<Prova.WCF.Client.ServiceReference.Cliente[]> GetClientiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClienteById", ReplyAction="http://tempuri.org/IService/GetClienteByIdResponse")]
        Prova.WCF.Client.ServiceReference.Cliente GetClienteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClienteById", ReplyAction="http://tempuri.org/IService/GetClienteByIdResponse")]
        System.Threading.Tasks.Task<Prova.WCF.Client.ServiceReference.Cliente> GetClienteByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddNewCliente", ReplyAction="http://tempuri.org/IService/AddNewClienteResponse")]
        bool AddNewCliente(Prova.WCF.Client.ServiceReference.Cliente newCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddNewCliente", ReplyAction="http://tempuri.org/IService/AddNewClienteResponse")]
        System.Threading.Tasks.Task<bool> AddNewClienteAsync(Prova.WCF.Client.ServiceReference.Cliente newCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditCliente", ReplyAction="http://tempuri.org/IService/EditClienteResponse")]
        bool EditCliente(Prova.WCF.Client.ServiceReference.Cliente updatedCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditCliente", ReplyAction="http://tempuri.org/IService/EditClienteResponse")]
        System.Threading.Tasks.Task<bool> EditClienteAsync(Prova.WCF.Client.ServiceReference.Cliente updatedCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteClienteById", ReplyAction="http://tempuri.org/IService/DeleteClienteByIdResponse")]
        bool DeleteClienteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteClienteById", ReplyAction="http://tempuri.org/IService/DeleteClienteByIdResponse")]
        System.Threading.Tasks.Task<bool> DeleteClienteByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Prova.WCF.Client.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Prova.WCF.Client.ServiceReference.IService>, Prova.WCF.Client.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Prova.WCF.Client.ServiceReference.Cliente[] GetClienti() {
            return base.Channel.GetClienti();
        }
        
        public System.Threading.Tasks.Task<Prova.WCF.Client.ServiceReference.Cliente[]> GetClientiAsync() {
            return base.Channel.GetClientiAsync();
        }
        
        public Prova.WCF.Client.ServiceReference.Cliente GetClienteById(int id) {
            return base.Channel.GetClienteById(id);
        }
        
        public System.Threading.Tasks.Task<Prova.WCF.Client.ServiceReference.Cliente> GetClienteByIdAsync(int id) {
            return base.Channel.GetClienteByIdAsync(id);
        }
        
        public bool AddNewCliente(Prova.WCF.Client.ServiceReference.Cliente newCliente) {
            return base.Channel.AddNewCliente(newCliente);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewClienteAsync(Prova.WCF.Client.ServiceReference.Cliente newCliente) {
            return base.Channel.AddNewClienteAsync(newCliente);
        }
        
        public bool EditCliente(Prova.WCF.Client.ServiceReference.Cliente updatedCliente) {
            return base.Channel.EditCliente(updatedCliente);
        }
        
        public System.Threading.Tasks.Task<bool> EditClienteAsync(Prova.WCF.Client.ServiceReference.Cliente updatedCliente) {
            return base.Channel.EditClienteAsync(updatedCliente);
        }
        
        public bool DeleteClienteById(int id) {
            return base.Channel.DeleteClienteById(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteClienteByIdAsync(int id) {
            return base.Channel.DeleteClienteByIdAsync(id);
        }
    }
}
